### ISSUE TITLE
Medaka

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#361] opened 2024-07-04 09:45 UTC
* link to support ticket: [2024070360000842](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=161110)
* website: https://github.com/nanoporetech/medaka
* installation docs: https://github.com/nanoporetech/medaka
* ~~toolchain: `foss/2023b`~~
* toolchain: `foss/2023a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * [ ] 
* optional dependencies:
  * [ ] Flye
  * [ ] Dorado
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by boegel** [comment] 2024-07-04 16:25
duplicate of #352, see PR for CPU-only version:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/20865

GPU variant requires:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/20358

**Comment by pavelToman** [comment] 2024-07-11 09:05
#362, https://github.com/vscentrum/vsc-software-stack/issues/361 and https://github.com/vscentrum/vsc-software-stack/issues/360 need to be compatible because the user wants to use them together

**Comment by pavelToman** [comment] 2024-08-02 11:51
After meeting 2/8/24 -> stick to foss/2023a not 2023b

**Comment by boegel** [comment] 2024-08-21 07:55
PR for medaka 1.12.0 with CUDA was opened by @PetrKralCZ, and is merged:

* https://github.com/easybuilders/easybuild-easyconfigs/pull/21210

I've also opened PRs for the latest medaka 1.12.1, which were trivial updates:

* https://github.com/easybuilders/easybuild-easyconfigs/pull/21214
* https://github.com/easybuilders/easybuild-easyconfigs/pull/21215

Ready for cleanup & closing!

**Closed as completed** 2024-08-21 09:09 UTC
Labels: difficulty: easy, priority: medium, Python, update, site:ugent, GPU
