### ISSUE TITLE
MONAI v1.3.0

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#248] opened 2023-12-19 09:43 UTC
* link to support ticket: [#2023112260000863](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=139757) + [#2024020860000217](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=146564)
* website: https://monai.io/
* installation docs: https://docs.monai.io/en/latest/installation.html
* toolchain: `foss/2022a`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [ ] https://github.com/Project-MONAI/MONAI/blob/dev/requirements-dev.txt
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (https://anaconda.org/conda-forge/monai) 
  * container image: yes (https://docs.monai.io/en/latest/installation.html#from-dockerhub)
  * pre-built binaries (RHEL8 Linux x86_64):  no
  * easyconfig outside EasyBuild: yes

**Comment by boegel** [comment] 2024-02-13 14:26
see https://github.com/easybuilders/easybuild-easyconfigs/pull/19598

**Comment by PetrKralCZ** [comment] 2024-05-07 15:24
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20493
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20494

**Comment by PetrKralCZ** [comment] 2024-05-07 15:30
Surprisingly MONAI (https://github.com/easybuilders/easybuild-easyconfigs/pull/20494) build fails with:
```
/apps/gent/RHEL8/cascadelake-ib/software/pybind11/2.11.1-GCCcore-12.3.0/include/pybind11/detail/../cast.h:45:120: error: expected template-name before < token
         45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
            |                                                                                                                        ^
      /apps/gent/RHEL8/cascadelake-ib/software/pybind11/2.11.1-GCCcore-12.3.0/include/pybind11/detail/../cast.h:45:120: error: expected identifier before < token
      /apps/gent/RHEL8/cascadelake-ib/software/pybind11/2.11.1-GCCcore-12.3.0/include/pybind11/detail/../cast.h:45:123: error: expected primary-expression before > token
         45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
            |                                                                                                                           ^
      /apps/gent/RHEL8/cascadelake-ib/software/pybind11/2.11.1-GCCcore-12.3.0/include/pybind11/detail/../cast.h:45:126: error: expected primary-expression before ) token
         45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
            |                                                                                                                              ^
```
The non-`CUDA` version works and these are the only differences:

```diff
--- /user/gent/453/vsc45304/easyconfigs/m/MONAI/MONAI-1.3.0-foss-2023a.eb       2024-02-13 14:26:27.200431393 +0100
+++ MONAI-1.3.0-foss-2023a-CUDA-12.1.1.eb       2024-05-07 10:21:18.970757232 +0200
@@ -2,6 +2,7 @@
 
 name = 'MONAI'
 version = '1.3.0'
+versionsuffix = '-CUDA-%(cudaver)s'
 
 homepage = 'https://monai.io/'
 description = """
@@ -19,16 +20,17 @@
 ]
 
 dependencies = [
+    ('CUDA', '12.1.1', '', SYSTEM),
     ('Python', '3.11.3'),
     ('Python-bundle-PyPI', '2023.06'),
     ('SciPy-bundle', '2023.07'),
-    ('PyTorch', '2.1.2'),
+    ('PyTorch', '2.1.2', versionsuffix),
     ('einops', '0.7.0'),
     ('ITK', '5.3.0'),
     ('NiBabel', '5.2.0'),
     ('scikit-image', '0.22.0'),
     ('tensorboard', '2.15.1'),
-    ('torchvision', '0.16.0'),
+    ('torchvision', '0.16.0', versionsuffix),
     ('tqdm', '4.66.1'),
     ('Pillow', '10.0.0'),
     ('openslide-python', '1.3.1'),
```

**Comment by boegel** [comment] 2024-05-07 15:39
@lexming Does this happen to ring any bells for you?

**Comment by lexming** [comment] 2024-05-08 07:18
The issue is not with MONAI but `pybind11`, I suggest to reinstall pybind11 in the cascadelakes. That installation might lack some patches, like https://github.com/easybuilders/easybuild-easyconfigs/pull/19047

**Comment by boegel** [comment] 2024-05-23 17:45
Thanks a lot for the help on this one @lexming!

@PetrKralCZ PRs merged, software installed, ready for cleanup & closing...

**Closed as completed** 2024-05-24 06:43 UTC
Labels: difficulty: medium, priority: medium, Python, update, site:t1_ugent_hortense, conda, container, easyconfig
