### ISSUE TITLE
medaka

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#188] opened 2023-07-31 09:12 UTC
* link to support ticket: [#2023072860000271](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=126026) + [#2023082360000751](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=127848)
* website: https://github.com/nanoporetech/medaka
* installation docs: https://github.com/nanoporetech/medaka
* toolchain: ``
* easyblock to use: `PythonBundle'
* required dependencies:
  * [ ] Python with cffi == 1.15.0
  OR
  * [x] #195
  * [ ] Tensorflow ~= v2.8.0 
* optional dependencies:
  * 
* notes:
  * latest version of medaka (currently 1.8.1)
* effort: *(TBD)*
* other install methods
  * conda: yes (https://github.com/nanoporetech/medaka)
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by RVerschoren** [comment] 2023-08-02 09:49
We received a similar request, for a more recent medaka version (>=1.6, so 1.8.1 fits the bill). I am looking into an installation in foss-2022a. The intervaltree-python, ont-fast5-api, Racon packages will need an update as well in that case.

**Comment by RVerschoren** [comment] 2023-08-04 09:14
Pushed current .eb files to [a wip directory](https://github.com/vscentrum/vsc-software-stack/tree/56321521c23c3e87beea8af63563bed96a478956/188_medaka). Still having some trouble with the hard dependency on TensorFlow 2.8.

**Comment by boegel** [comment] 2023-08-04 10:46
@RVerschoren It may be OK to just loosen up that strict version requirement for TensorFlow 2.8, see also my question to them on this a while ago: https://github.com/nanoporetech/medaka/issues/124

**Comment by RVerschoren** [comment] 2023-08-04 17:05
@boegel Thanks for the suggestion! It seems the error is in the sanity check part.

Both commands in the EasyConfig's sanity_check_commands work successfully, but a `python -m pip check` is also run. That blocks on the `tensorflow~=2.8.0` line in `requirements.txt`.

I made a quick patch for that to accept other versions, and tested that with both TensorFlow 2.9 and 2.11 versions in foss-2022a.
The package now builds and installs a module fine for both. However, executing the `make test` mentioned in nanoporetech/medaka#124 only seems to run a coverage report in 3 collected tests. That coverage is about 18% of the code, so it fails to clear the 80% COVFAIL threshold they set in the Makefile.

~~Looking for the test files, I came across your other post nanoporetech/medaka#125. It seems they no longer ship a medaka/test directory and I did not find the CI pipeline they mentioned there (broken link to the walkthrough). I don't see much to test the installation here...~~

**Edit:** Requester linked me to the [medaka/test/data](https://github.com/nanoporetech/medaka/tree/master/medaka/test/data) in the GitHub repo itself. I will check it out.

**Comment by boegel** [comment] 2023-08-24 09:41
@RVerschoren Any updates on this? We now also have 2 researchers who would like to see an updated version of `medaka`

**Comment by RVerschoren** [comment] 2023-08-24 10:02
I re-installed with Pysam 0.19.1 (avoiding the version conflict we discussed during the last meeting).

Our requester is trying to test it, but keeps running into memory issues: with 3-day jobs that keep failing 2 days in, this is going slow. Unfortunately, it doesn't seem they have any other test input...

The medaka tests still report a coverage of 89% for me. Not ideal, but it looks to me like it installs and can be used as intended.

That said, I would appreciate additional testing on other sites, or other suggestions or advice on how to proceed.

**Comment by boegel** [comment] 2023-08-24 10:05
@RVerschoren That sounds like it ready for tinkering with by researchers who actually need it...

Do you think it makes sense to open a pull request for your `medaka` easyconfig + whatever else is needed (patch files, easyconfigs for dependencies) to the central easyconfigs repo?

**Comment by RVerschoren** [comment] 2023-08-24 10:10
@boegel There is nothing specific to UAntwerp or VSC in it, so yes, it can be shared, both in the VSC as well as the easybuilders-easyconfigs repository.

**Comment by RVerschoren** [comment] 2023-08-24 15:16
Sent PR to central easyconfigs, easybuilders/easybuild-easyconfigs#18639

**Comment by boegel** [comment] 2023-08-25 13:21
@RVerschoren PR merged, so the corresponding directory in `wip` branch can be cleaned up, and this issue can be closed

**Comment by boegel** [comment] 2023-08-25 16:06
@RVerschoren I noticed there were several more recent releases of `medaka`, so I've done a trivial update in https://github.com/easybuilders/easybuild-easyconfigs/pull/18651

**Comment by RVerschoren** [comment] 2023-08-30 14:09
@boegel Thank you for the update, I missed the last releases.

I cleaned up the corresponding `wip` directory, so I'm closing this issue.

**Closed as completed by RVerschoren** 2023-08-30 14:09 UTC
Labels: difficulty: medium, priority: medium, site:ugent, conda, easyconfig
