### ISSUE TITLE
Limbo

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#392] opened 2024-08-22 09:21 UTC
* link to support ticket: [#2024082160000897](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=165473)
* website: https://resibots.eu/limbo/
* installation docs: https://resibots.eu/limbo/tutorials/compilation.html#
* toolchain: `GCC/12.3.0` or older
* ~~easyblock to use: `CMake?`~~
* easyblock to use: `Waf`
* required dependencies:
  * [x] Boost
  * [x] Eigen
* optional dependencies: (The are optional but they do recommend adding them in the docs
  * [x] Intel TBB?
  * [x] NLOPT
  * [x] libcmaes
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by pavelToman** [comment] 2024-08-29 07:33
Could you please ask user why they need Limbo and how they will use it? I can build it now, but it creates only the /bin dir with some executables (not limbo) which seems to be used by waf and Limbo. (/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/Limbo/2.1.0-20231019-foss-2023a/bin).
It seems the Limbo is some framework that needs waf to create experiments - you can then create your own .cpp files and easily build it and test it. The problem is that it counts that the build dir with waf executable still exists (which is not without buildininstalldir = True) and it will create the experiments folders in installdir - which is unchangeable for users - so they could not create any experiment.

**Comment by boegel** [comment] 2024-08-29 09:39
@pavelToman Can you try if the `exp/myExp` directory from the [basic example](https://resibots.eu/limbo/tutorials/basic_example.html) can be put somewhere else, outside of the Limbo installation directory?
That means that you'll need to change the `includes` bit in the `wscript` file to use `$EBROOTLIMBO/limbo/src` probably instead of `../../src` (and maybe change the `.` to `$EBROOTLIMBO`, not sure).

And then run `waf build ...` (not `./waf build ...`), since `waf` will be part of the Limbo installation, and be available via `$PATH`.

To check whether it's not making changes in the Limbo install dir, make sure it's installed with `eb --read-only-installdir`

If that doesn't work, we either:
* patch Limbo so it always creates experiments in `$HOME/limbo` instead of in Limbo install dir (hopefully not needed);
* install Limbo in the VSC account of the researcher, where they can change the Limbo installation dir;

If `waf` always needs to be run with specific options, we can define an alias in the module file, via this in the easyconfig:
```python
modaliases = {
    'waf': "waf -option1 -option2",
}

**Comment by boegel** [comment] 2024-08-29 09:45
Maybe we can also ask upstream whether a central (read-only) installation of Limbo makes sense, see https://github.com/resibots/limbo/issues

**Comment by boegel** [comment] 2024-08-29 16:50
@pavelToman installation request for Limbo has been cancelled, so stop working on it.

If we need to pick up on this again, we can pull the draft easyconfigs from Git history, so do go ahead and cleanup + close this issue.

**Closed as completed** 2024-08-30 08:44 UTC
Labels: difficulty: medium, C/C++, new, priority: ASAP, site:t1_ugent_hortense
