### ISSUE TITLE
TF-COMB

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#302] opened 2024-03-15 10:43 UTC
* link to support ticket: [#2024030460000277](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=149261)
* website: https://github.com/loosolab/TF-COMB
* installation docs: https://github.com/loosolab/TF-COMB
* toolchain: `foss/2023a`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [x] Python
  * [x] Cython
* optional dependencies:
  * [x] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?)
  * container image:  no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by pavelToman** [comment] 2024-05-27 16:16
There is a problem with TF-COMB and python 3.11.
The problem is with this old C-file: https://github.com/loosolab/TF-COMB/blob/4678b17b87833cfb7b38d5513f2fbf8cf35dc401/tfcomb/counting.c#L198
Error:
```
   error: longintrepr.h: No such file or directory
   #include "longintrepr.h"
```
Replace `#include "longintrepr.h"` by `#include "Python.h"` does not work. It complains about PyCode_New() function. Seems the solution is to update old .c file (https://github.com/amueller/word_cloud/issues/691) or use python 3.10.
Same problem as: https://easybuild.slack.com/archives/C34UA1HT7/p1716387781812609

Update:
TF-COMB for foss/2022b works.
Update the counting.c by `cythonize` by newer cython works for foss/2023a, but there is another error:
During "import tfcomb" the Seaborn wants to "from statistics import NormalDist" but there is another package "statistics" in svist4get and there is no NormalDist like in python lib.

Update_2:
"statistics" in svist4get is 10y old package to provide "statistics" to older python, not useful anymore. Without it the foss/2023a version works.

**Comment by pavelToman** [comment] 2024-05-27 18:42
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20665

**Comment by pavelToman** [comment] 2024-05-28 11:05
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20666

**Comment by boegel** [comment] 2024-06-04 16:49
@pavelToman PR merged, software installed, ready for cleanup

**Closed as completed** 2024-06-05 08:43 UTC
Labels: difficulty: easy, new, priority: medium, Python, site:ugent, conda
