### ISSUE TITLE
Finder

### ISSUE THREAD

**Issue by hajgato** [vscentrum/vsc-software-stack#21] opened 2022-07-29 06:52 UTC
* link to support ticket: [#2022072860000255](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=86564)
* website: https://github.com/sagnikbanerjee15/Finder
* installation docs: https://github.com/sagnikbanerjee15/Finder#downloading-finder-from-release-latest-stable-version
* toolchain: `foss/2021b`
* easyblock to use: ???
* required dependencies:
  * [ ] BRAKER https://github.com/vscentrum/vsc-software-stack/issues/20
  * optional dependencies:
  * [ ] ...
* notes:
  * Might be a tricky one, as it wants to download a docker/singularity image and run the software in the image....
* effort: *(TBD)*

**Comment by deniskristak** [comment] 2022-09-12 14:50
PsiCLASS is one of deps - opened PR

**Comment by deniskristak** [comment] 2022-10-18 14:22
https://github.com/sagnikbanerjee15/Finder/issues/64
opened issue, asking about the way to avoid docker/singularity

**Comment by deniskristak** [comment] 2022-10-18 14:26
the problem is that there will be a whole lot of patching
https://github.com/sagnikbanerjee15/Finder/blob/master/run_finder
as the main script pulls docker image everytime you run it...

**Comment by deniskristak** [comment] 2022-10-18 14:27
so i just asked if anyone did it before

**Comment by deniskristak** [comment] 2022-12-15 11:37
PR opened

**Comment by boegel** [comment] 2023-01-24 08:52
https://github.com/easybuilders/easybuild-easyconfigs/pull/16910 merged, ready for cleanup \o/

**Comment by deniskristak** [comment] 2023-01-26 11:31
cleaned up

**Closed by deniskristak** 2023-01-26 11:31 UTC
Labels: difficulty: hard, new, priority: high, Python, site:ugent, site:t1_ugent_hortense
